#!/bin/bash

for name in $1.*
do
	if echo $name | awk -v FS=. -v max=$2 '$2<max {exit 1}'
	then
		rm $name
	else
		mv $name .rotate.`echo $name | awk -v FS=. '{print ($2+1)}'`.$name
	fi
done
for name in .rotate.*
do
	mv $name $1.`echo $name | awk -v FS=. '{print $3}'`
done
if [[ -f $1 ]]
then
	mv $1 $1.0
fi
